---
autoCorrect: true
failFast: false
build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    formatting: 1
processors:
  active: true
  exclude:
  - "**/generated/**"
config:
  validation: true
comments:
  CommentOverPrivateFunction:
    active: true
    allowedPatterns: []
complexity:
  TooManyFunctions:
    active: true
    threshold: 10
  LongMethod:
    active: true
    threshold: 30
  ComplexMethod:
    active: true
    threshold: 15
formatting:
  active: true
  autoCorrect: true
  android: false
  disabledRules: []
style:
  MagicNumber:
    active: true
    ignoreNumbers:
    - -1
    - 0
    - 1
    - 2
  NamingConventionViolation:
    active: true
  ForbiddenComment:
    active: true
    values:
    - "FIXME"
    - "BUG"
    - "TODO"
performance:
  active: true
potential-bugs:
  active: true
exceptions:
  active: true
