build:
  maxIssues: 150
  weights:
    complexity: 2
    style: 1
processors:
  active: true
  exclude:
    - "**/generated/**"
config:
  validation: true

comments:
  CommentOverPrivateFunction:
    active: true

complexity:
  LongMethod:
    active: true
    threshold: 30
  CyclomaticComplexMethod:
    active: true
    threshold: 15

style:
  MagicNumber:
    active: true
    ignoreNumbers:
      - "-1"
      - "0"
      - "1"
      - "2"

performance:
  active: true

potential-bugs:
  active: true

exceptions:
  active: true