name: Build and Publish Plugin

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: write  # Needed for pushing tags/commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Gradle Files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Set up Git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # Ensure remote uses token-based HTTPS auth
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/tabano86/ClipCraft.git

      - name: Fetch and Sync Remote Tags
        run: |
          # Fetch the latest tags and reset the local branch
          git fetch --prune --tags
          git reset --hard origin/main

      - name: Run Release with Retry
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          max_attempts=3
          attempt=1
          until ./gradlew release --no-daemon --stacktrace; do
            if [ $attempt -ge $max_attempts ]; then
              echo "Release failed after $attempt attempts."
              exit 1
            fi
            echo "Release attempt $attempt failed, retrying in 10 seconds..."
            sleep 10
            attempt=$((attempt + 1))
          done

      - name: Debug Plugin Token
        run: echo "JB_PLUGIN_REPOSITORY_TOKEN = '${JB_PLUGIN_REPOSITORY_TOKEN}'"
        env:
          JB_PLUGIN_REPOSITORY_TOKEN: ${{ secrets.JB_PLUGIN_REPOSITORY_TOKEN }}

      - name: Run Tests
        run: ./gradlew clean test --no-daemon --stacktrace

      - name: Build Plugin
        run: ./gradlew clean buildPlugin --no-daemon --stacktrace

      - name: Patch Plugin XML
        run: ./gradlew patchPluginXml --no-daemon --stacktrace

      - name: Publish Plugin
        if: github.event_name == 'push'
        env:
          JB_PLUGIN_REPOSITORY_TOKEN: ${{ secrets.JB_PLUGIN_REPOSITORY_TOKEN }}
        run: ./gradlew publishPlugin \
          -Dorg.jetbrains.intellij.pluginRepository.publish.token=$JB_PLUGIN_REPOSITORY_TOKEN \
          --no-daemon --stacktrace
