name: Build and Publish Plugin

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Confirm gradlew permissions
        run: ls -l ./gradlew

      - name: Disable file mode changes
        run: git config core.fileMode false

      - name: Reset repository to clean state
        run: |
          git reset --hard
          git clean -fdx

      - name: Cache Gradle Files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run Release (Bump version and tag)
        if: github.event_name == 'push'
        run: bash ./gradlew release --no-daemon --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Run Tests
      #        run: bash ./gradlew clean test --no-daemon --stacktrace

      - name: Build Plugin
        run: bash ./gradlew clean buildPlugin --no-daemon --stacktrace

      - name: Patch Plugin XML
        run: bash ./gradlew patchPluginXml --no-daemon --stacktrace

      - name: Publish Plugin
        if: github.event_name == 'push'
        env:
          JB_PLUGIN_REPOSITORY_TOKEN: ${{ secrets.JB_PLUGIN_REPOSITORY_TOKEN }}
        run: bash ./gradlew publishPlugin -PpublishToken=$JB_PLUGIN_REPOSITORY_TOKEN --no-daemon --stacktrace
