package com.clipcraft.model

data class SettingsState(
    var includeGlobs: String = """
        **/*.kt
        **/*.java
        **/*.go
        **/*.py
        **/*.js
        **/*.ts
        **/*.tsx
        **/*.jsx
        **/*.html
        **/*.css
        **/*.scss
        **/*.svelte
        **/*.vue
        **/*.md
        **/*.xml
        **/*.json
        **/*.yml
        **/*.yaml
        **/*.toml
        **/*.sh
        **/*.properties
        **/*.sql
        **/Dockerfile*
        **/*.Dockerfile*
        **/*docker-compose*.yml
        **/Makefile
        **/*.gradle.kts
        **/pom.xml
        **/pyproject.toml
        **/package.json
        **/tsconfig.json
    """.trimIndent(),
    var excludeGlobs: String = """
        **/build/**
        **/.gradle/**
        **/.idea/**
        **/.git/**
        **/node_modules/**
        **/.venv/**
        **/dist/**
        **/.next/**
        **/.svelte-kit/**
        **/.output/**
        **/.turbo/**
        **/target/**
        **/*__pycache__/**
        **/.pytest_cache/**
        **/*.class
        **/*.jar
        **/*.bin
        **/poetry.lock
        **/pnpm-lock.yaml
        **/yarn.lock
        **/package-lock.json
        **/*.pyc
        **/*.log*
        **/*.so
        **/*.dll
        **/*.exe
        **/*.dmg
        **/*.iso
        **/*.zip
        **/*.tar.gz
    """.trimIndent(),
    var maxFileSizeKb: Int = 2048
)